Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "sh-apache2-php7"

  config.vm.synced_folder "www/", "/var/www/", create: true

  config.vm.network :private_network, ip: "192.168.99.150"

  config.vm.provision :shell, :path => "setup.sh"
end